# Generated by Django 2.0.2 on 2019-05-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
