# Generated by Django 2.0.2 on 2019-05-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='body',
        ),
    ]
