# Generated by Django 2.0.2 on 2019-05-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title1',
            field=models.CharField(default='SOME STRING', max_length=125),
        ),
    ]
